package model

import "strings"

// Generated from new-api-sync VENDOR_MATCHERS. Keep in sync when matchers change.
// Pattern-matches a model name to a vendor when no explicit vendor_id exists
// (used by rankings for logged-but-unrouted models).

type vendorPattern struct {
	pattern string
	vendor  string
	strong  bool
}

var vendorPatterns = []vendorPattern{
	{"claude", "Anthropic", false},
	{"gemini", "Google", false},
	{"palm", "Google", false},
	{"veo", "Google", false},
	{"gemma", "Google", false},
	{"lyria", "Google", false},
	{"imagen", "Google", false},
	{"embedding-001", "Google", false},
	{"embedding-gecko", "Google", false},
	{"text-embedding-004", "Google", false},
	{"gpt", "OpenAI", false},
	{"o1-", "OpenAI", false},
	{"o3", "OpenAI", false},
	{"o4-", "OpenAI", false},
	{"chatgpt", "OpenAI", false},
	{"sora", "OpenAI", false},
	{"text-embedding-3", "OpenAI", false},
	{"text-embedding-ada", "OpenAI", false},
	{"whisper", "OpenAI", false},
	{"dall-e", "OpenAI", false},
	{"tts-1", "OpenAI", false},
	{"omni-moderation", "OpenAI", false},
	{"openai", "OpenAI", false},
	{"kling", "Kling", false},
	{"deepseek", "DeepSeek", false},
	{"grok", "xAI", false},
	{"mistral", "Mistral", false},
	{"codestral", "Mistral", false},
	{"devstral", "Mistral", false},
	{"magistral", "Mistral", false},
	{"ministral", "Mistral", false},
	{"voxtral", "Mistral", false},
	{"pixtral", "Mistral", false},
	{"jina-", "Jina AI", false},
	{"bge-", "BAAI", false},
	{"bce-embedding", "BAAI", false},
	{"baai/", "BAAI", false},
	{"baichuan", "Baichuan", false},
	{"llama", "Meta", false},
	{"nemotron", "NVIDIA", true},
	{"lfm-", "Liquid", false},
	{"ling-", "InclusionAI", false},
	{"ring-", "InclusionAI", false},
	{"hermes-", "Nous Research", false},
	{"mythomax", "Gryphe", true},
	{"mythomist", "Gryphe", false},
	{"mythalion", "Gryphe", true},
	{"mytho-", "Gryphe", false},
	{"venice", "Venice AI", false},
	{"qwen", "Alibaba", false},
	{"qwq-", "Alibaba", false},
	{"text-embedding-v", "Alibaba", false},
	{"wan2", "Bailian", false},
	{"z-image", "Bailian", false},
	{"flux-", "Flux", false},
	{"flux.", "Flux", false},
	{"flux", "Flux", false},
	{"command-", "Cohere", false},
	{"c4ai-", "Cohere", false},
	{"cohere", "Cohere", false},
	{"aya-", "Cohere", false},
	{"tiny-aya", "Cohere", false},
	{"north-mini", "Cohere", false},
	{"embed-english-", "Cohere", false},
	{"embed-multilingual-", "Cohere", false},
	{"embed-v4", "Cohere", false},
	{"abab", "MiniMax", false},
	{"minimax-", "MiniMax", false},
	{"moonshot-", "Moonshot", false},
	{"kimi-", "Moonshot", false},
	{"kimi", "Moonshot", false},
	{"k2.6", "Moonshot", false},
	{"k2-", "Moonshot", false},
	{"glm-", "Zhipu", false},
	{"glm4", "Zhipu", false},
	{"glm5", "Zhipu", false},
	{"glm6", "Zhipu", false},
	{"chatglm", "Zhipu", false},
	{"sonar", "Perplexity", false},
	{"ernie-", "Baidu", false},
	{"qianfan-", "Baidu", false},
	{"embedding-v1", "Baidu", false},
	{"sparkdesk", "Xunfei", false},
	{"hunyuan-", "Tencent", false},
	{"hy3-", "Tencent", false},
	{"hy4-", "Tencent", false},
	{"hy-mt", "Tencent", false},
	{"doubao-", "ByteDance", false},
	{"seed-", "ByteDance", false},
	{"sdxl-lightning", "ByteDance", true},
	{"stable-diffusion", "Stability AI", false},
	{"stability", "Stability AI", false},
	{"sdxl", "Stability AI", false},
	{"eleven-", "ElevenLabs", false},
	{"eleven_", "ElevenLabs", false},
	{"elevenlabs", "ElevenLabs", false},
	{"eleven-multilingual", "ElevenLabs", false},
	{"eleven-turbo", "ElevenLabs", false},
	{"eleven-flash", "ElevenLabs", false},
	{"speechify", "Speechify", false},
	{"deepl", "DeepL", true},
	{"rnj-", "Essential AI", true},
	{"longcat", "Meituan", true},
	{"kat-coder", "Kuaishou", true},
	{"kat-dev", "Kuaishou", true},
	{"kwaipilot", "Kuaishou", false},
	{"internlm", "InternLM", true},
	{"internvl", "InternLM", true},
	{"intern-s", "InternLM", true},
	{"intern-latest", "InternLM", false},
	{"sensechat", "SenseNova", true},
	{"sensenova", "SenseNova", true},
	{"sense-", "SenseNova", false},
	{"umbra", "VoidAI", true},
	{"zanity-rp", "Zanity", true},
	{"zanity", "Zanity", false},
	{"yi-", "Yi", false},
	{"360gpt", "360 AI", false},
	{"mimo-", "Xiaomi", false},
	{"arcee", "Arcee AI", false},
	{"trinity", "Arcee AI", false},
	{"afm-", "Arcee AI", false},
	{"virtuoso-", "Arcee AI", false},
	{"maestro-", "Arcee AI", false},
	{"caller-", "Arcee AI", false},
	{"blitz", "Arcee AI", false},
	{"spotlight", "Arcee AI", false},
	{"coder-large", "Arcee AI", false},
	{"compound", "Groq", false},
	{"allam", "SDAIA", false},
	{"granite-", "IBM", false},
	{"mellum", "JetBrains", true},
	{"abliterated", "Abliteration", true},
	{"bielik", "SpeakLeash", true},
	{"pllum", "PLLuM", true},
	{"villanova", "Villanova", true},
	{"mercury", "Inception", true},
	{"phi-", "Microsoft", false},
	{"phi4", "Microsoft", false},
	{"wizardlm", "Microsoft", false},
	{"aura-", "Deepgram", false},
	{"nova-3", "Deepgram", false},
	{"nova-2", "Deepgram", false},
	{"phoenix-", "Leonardo AI", false},
	{"lucid-", "Leonardo AI", false},
	{"melotts", "MyShell", false},
	{"plamo", "Preferred Networks", false},
	{"dreamshaper", "Lykon", false},
	{"nova", "Amazon", false},
	{"polly", "Amazon", false},
	{"titan-", "Amazon", false},
	{"midijourney", "Pollinations", false},
	{"openai-fast", "Pollinations", false},
	{"openai-large", "Pollinations", false},
	{"openai-roblox", "Pollinations", false},
	{"openai-audio", "Pollinations", false},
	{"cydonia", "TheDrummer", false},
	{"skyfall", "TheDrummer", false},
	{"behemoth", "TheDrummer", false},
	{"rocinante", "TheDrummer", false},
	{"magidonia", "TheDrummer", false},
	{"tiger-gemma", "TheDrummer", false},
	{"nex-n2", "Nex AGI", false},
	{"nex-agi", "Nex AGI", false},
	{"laguna", "Poolside", false},
	{"malibu", "Poolside", false},
	{"sea-lion", "AI Singapore", true},
	{"step-", "StepFun", false},
	{"step1", "StepFun", false},
	{"step2", "StepFun", false},
	{"step3", "StepFun", false},
	{"arch-router", "Katanemo", false},
	{"arch-function", "Katanemo", false},
	{"holo2", "H Company", false},
	{"holo-", "H Company", false},
	{"navy-roleplay", "NavyAI", false},
	{"devious-uncensored", "NavyAI", false},
	{"revenant-uncensored", "NavyAI", false},
	{"laborratse", "NavyAI", false},
	{"emotional-36b", "NavyAI", false},
	{"euryale", "Sao10K", true},
	{"stheno", "Sao10K", true},
	{"lunaris", "Sao10K", true},
	{"hanami", "Sao10K", false},
	{"fimbulvetr", "Sao10K", false},
	{"nevoria", "Steelskull", true},
	{"ms-nevoria", "Steelskull", false},
	{"steelskull", "Steelskull", false},
	{"sapphira", "BruhzWater", true},
	{"violet-lotus", "FallenMerick", true},
	{"mn-violet", "FallenMerick", false},
	{"manta-mini", "MegaNova", false},
	{"manta-flash", "MegaNova", false},
	{"manta-pro", "MegaNova", false},
	{"aion-rp", "Aion Labs", true},
	{"aion-1", "Aion Labs", false},
	{"aion-2", "Aion Labs", false},
	{"aion-3", "Aion Labs", false},
	{"lfm2", "Liquid", false},
	{"kinfra", "Kinfra", true},
	{"ornith", "DeepReinforce", true},
	{"big-pickle", "OpenCode Zen", true},
	{"opencode", "OpenCode Zen", false},
	{"orca-fusion", "OrcaRouter", true},
	{"orca-router", "OrcaRouter", true},
}

var vendorDisplayIcons = map[string]string{
	"Anthropic":     "Claude.Color",
	"Google":        "Gemini.Color",
	"OpenAI":        "OpenAI",
	"Kling":         "Kling.Color",
	"DeepSeek":      "DeepSeek.Color",
	"xAI":           "XAI",
	"Mistral":       "Mistral.Color",
	"Jina AI":       "Jina",
	"BAAI":          "BAAI",
	"Baichuan":      "Baichuan.Color",
	"Meta":          "Meta.Color",
	"NVIDIA":        "Nvidia.Color",
	"Liquid":        "Liquid",
	"Nous Research": "NousResearch",
	"Venice AI":     "Venice.Color",
	"Alibaba":       "AlibabaCloud.Color",
	"Bailian":       "AlibabaCloud.Color",
	"Flux":          "Flux",
	"Cohere":        "Cohere.Color",
	"MiniMax":       "Minimax.Color",
	"Moonshot":      "Moonshot",
	"Zhipu":         "Zhipu.Color",
	"Perplexity":    "Perplexity.Color",
	"Baidu":         "Wenxin",
	"Xunfei":        "Spark.Color",
	"Tencent":       "Hunyuan",
	"ByteDance":     "Doubao.Color",
	"Stability AI":  "Stability",
	"ElevenLabs":    "ElevenLabs",
	"InternLM":      "InternLM",
	"SenseNova":     "SenseNova",
	"Yi":            "Yi.Color",
	"360 AI":        "Ai360",
	"Xiaomi":        "Xiaomi",
	"Arcee AI":      "Arcee.Color",
	"Groq":          "Groq",
	"SDAIA":         "SDAIA",
	"StepFun":       "Stepfun.Color",
	"Inception":     "Inception",
	"Kinfra":        "Hunyuan",
}

// ResolveDefaultVendor returns the vendor display name + icon for a model name,
// replicating the sync VENDOR_MATCHERS scoring: strongPatterns win, then a
// prefix match, then the longest pattern. Empty strings when nothing matches.
func ResolveDefaultVendor(modelName string) (vendor string, icon string) {
	n := strings.ToLower(modelName)
	bestScore := -1
	bestVendor := ""
	for i := range vendorPatterns {
		p := vendorPatterns[i].pattern
		if !strings.Contains(n, p) {
			continue
		}
		score := len(p)
		if vendorPatterns[i].strong {
			score += 10000
		}
		if strings.HasPrefix(n, p) {
			score += 1000
		}
		if score > bestScore {
			bestScore = score
			bestVendor = vendorPatterns[i].vendor
		}
	}
	if bestVendor == "" {
		return "", ""
	}
	return bestVendor, vendorDisplayIcons[bestVendor]
}
